### ISSUE TITLE
I am new to itk.js and planning to use in my react application. Is there any tutorial/documentation/examples that I can refer?

### ISSUE THREAD

**Issue by Sneha-pk** [SimpleITK/TUTORIAL#22]
I have been trying to check out some or any documentation on itk.js.  Most of my search has led me to 404 error. Please let me know if I have missed any links that i may have missed.

**Comment by zivy** [comment]
Hello @Sneha-pk,

This question is with respect to itk.js and this repository is associated with the SimpleITK tutorial, so not the relevant forum. 

Please ask the question on the [ITK discourse](https://discourse.itk.org/).
