### ISSUE TITLE
Not able to read image in tutorial

### ISSUE THREAD

**Issue by Ilias-Paralikas** [SimpleITK/TUTORIAL#40]
I am following the [simpleITK tutorial](https://simpleitk.org/TUTORIAL/) and these two lines of code throw this error.

image_viewer = sitk.ImageViewer()
image_viewer.Execute(sitk.ReadImage(fetch_data(“SimpleITK.jpg”)))

Exception thrown in SimpleITK ImageFileReader_Execute: D:\a\1\sitk\Code\IO\src\sitkImageReaderBase.cxx:102:
sitk::ERROR: Unable to open “C:\Users\paral\OneDrive\Υπολογιστής\diplomatikh\TUTORIAL\data\SimpleITK.jpg” for reading.

Both the image and fiji are where they are supposed to be.

**Comment by zivy** [comment]
Closing this issue. It was cross-posted to the ITK discourse and [answered there](https://discourse.itk.org/t/simpleitk-tutorial-not-able-to-read-images/5859).
