### ISSUE TITLE
ImportError: DLL load failed while importing _SimpleITK: The specified module could not be found.

### ISSUE THREAD

**Issue by Ilias-Paralikas** [SimpleITK/TUTORIAL#41]
i had a problem with loading the image, so I uninstalled everything and followed the tutorial, but I get two different errors. 
First, when I type 
conda update anaconda
I get
PackageNotInstalledError: Package is not installed in prefix.
  prefix: C:\Users\paral\anaconda3
  package name: anaconda

Which can be bypassed with
conda install anaconda.

After that everything works fine until I open the notebook. When I try to import SimpleITK I get

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 import SimpleITK as sitk
      2 from downloaddata import fetch_data, fetch_data_all
      4 from ipywidgets import interact

File ~\anaconda3\envs\sitkpy\lib\site-packages\SimpleITK\__init__.py:18
      1 # ========================================================================
      2 #
      3 #  Copyright NumFOCUS
   (...)
     16 #
     17 # ========================================================================
---> 18 from SimpleITK.SimpleITK import *
     19 from SimpleITK.extra import *
     21 from SimpleITK._version import __version__

File ~\anaconda3\envs\sitkpy\lib\site-packages\SimpleITK\SimpleITK.py:13
     11 # Import the low-level C/C++ module
     12 if __package__ or "." in __name__:
---> 13     from . import _SimpleITK
     14 else:
     15     import _SimpleITK

ImportError: DLL load failed while importing _SimpleITK: The specified module could not be found.

I have re-installed anaconda python but nothing seems to work.

Edit: The first time import simpleITK worked fine. I have no clue what I did differently.

**Comment by zivy** [comment]
Hello @Ilias-Paralikas,

Possibly you activated the `sitkpy` environment before updating conda? If you follow the [installation instructions](https://simpleitk.org/TUTORIAL/#setup), you will first install anaconda and update the `base` environment, `conda update conda` and `conda update anaconda`. 

Please uninstall your anaconda installation and redo the setup process. If this does not resolve the issue, please provide the set of steps you took till encountering an error.

**Comment by Ilias-Paralikas** [comment]
Hello, 
so the steps after full uninstall of anaconda were:
download&run conda [installer](https://www.anaconda.com/products/distribution).
add C:\Users\paral\anaconda3 to environment variables.
Open anaconda prompt
conda update conda.  works fine.
conda update anaconda. 
I get this error
PackageNotInstalledError: Package is not installed in prefix.
prefix: C:\Users\paral\anaconda3
package name: anaconda

that I solve by installing anaconda( this step is not in the tutorial)
conda install anaconda 
conda update anaconda  works fine
conda install git
git clone https://github.com/SimpleITK/TUTORIAL.git
conda env create -f TUTORIAL/environment.yml
 conda activate sitkpy
cd TUTORIAL
jupyter notebook 00_setup.ipynb
run the first cell and I get the error from above

I follow the tutorial except from the conda install anaconda part.

**Comment by zivy** [comment]
Hello @Ilias-Paralikas,

It appears you uncovered a fault in the anaconda distribution of SimpleITK 2.2.1 for windows. We will look into this shortly.

For a quick workaround, please do the following:
1. Activate the environment: `conda activate sitkpy`.
2. Uninstall the SimpleITK anaconda package: `conda remove SimpleITK`
3. Install the SimpleITK vanilla Python package: `pip install SimpleITK`
4. Run the tutorial.

Please let us know if this resolved your issue or not.

**Comment by Ilias-Paralikas** [comment]
yeap, this worked fine. 
Thank you very much!
